#!/bin/sh

if git rev-parse --verify HEAD >/dev/null 2>&1
then
	against=HEAD
else
	# Initial commit: diff against an empty tree object
	against=4b825dc642cb6eb9a060e54bf8d69288fbee4904
fi

git diff --cached --name-only $against | while read line; do
echo $line;

# there should have no space between = and $.
content=$(git diff --cached $line)
re='\<asp:TextBox\b((?!MaxLength).)*>'

# echo "$content" will preserve spaces and newlines in the variable,
# whereas echo $content will replace these characters with a space.
if echo "$content" | grep -P --ignore-case $re
then
  echo You doo doo, you need to specify a maxLength attribute on ALL asp:textbox elements
  exit 1
fi
done
